from discord.ext import commands
import random


class RandomCommands(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(name="coinflip", description="jay_bot flips a coin", aliases=["flip", "flipcoin"])
    async def coinflip(self, ctx):
        await ctx.send(f"{random.choice(['heads', 'tails'])}")

    @commands.command(name="roll", description="jay_bot rolls a dice")
    async def roll(self, ctx, amount=1):
        if amount == 1:
            await ctx.send(f"You rolled a {random.randrange(1, 7)}.")
        elif amount > 1:
            rolls = [random.randrange(1, 7) for _ in range(amount)]
            concatenation = ", ".join(map(str, rolls))
            await ctx.send(f"You rolled {concatenation} = {sum(rolls)}.")

    @commands.command(name="percent", description="jay_bot gives you a percent")
    async def percent(self, ctx, *, question):
        await ctx.send(f"{random.randrange(0, 101)}%")

    @commands.command(name="8ball", description="jay_bot answers your questions")
    async def _8ball(self, ctx, *, question):
        responses = ["As I see it, yes",
                     "Ask again later",
                     "Better not tell you now",
                     "Cannot predict now",
                     "Concentrate and ask again",
                     "Don't count on it",
                     "It is certain",
                     "It is decidedly so",
                     "Most likely",
                     "My reply is no",
                     "Outlook not so good",
                     "Outlook good",
                     "Reply hazy, try again",
                     "Signs point to yes",
                     "Very doubtful",
                     "Without a doubt",
                     "Yes",
                     "Yes - definitely",
                     "You may rely on it"]
        await ctx.send(random.choice(responses))

    @commands.command(name="teams", description="jay_bot randomizes team members")
    async def teams(self, ctx, *, members):
        teams = [[], []]
        delimiter = ", "
        members = members.split(delimiter)
        i = 0

        while members:
            randInt = random.randrange(0, len(members))
            member = members.pop(randInt)
            teams[i].append(member)
            i += 1
            i %= 2

        await ctx.send(f"Team A: {delimiter.join(teams[0])}\nTeam B: {delimiter.join(teams[1])}")

    @commands.command(name="madgab", aliases=["mg"])
    async def madgab(self, ctx):
        prompts = {"Abe Odd Hull Luck Oak": "A bottle of Coke",
                   "Ace Lip Puff That Hung": "A slip of the tongue",
                   "Ace Tray Taste Who Dent": "A straight A student",
                   "Aid Are Crank Loud": "A dark rain cloud",
                   "Bat Tree Snot Ink Looted": "Batteries not included",
                   "Canoe Key Pass Egret": "Can you keep a secret?",
                   "Cohen Peas": "Go in peace",
                   "Cry Cub Hook": "Crack a book",
                   "Dawn dude rugs": "Don't do drugs",
                   "Delete Elmer Made": "The little mermaid",
                   "Dew Ache Who Gulls Urge": "Do a Google search",
                   "Ease Owner Whole": "He's on a roll",
                   "Eye Mull of Mush Sheen": "I'm a love machine",
                   "Freeze Age Ha! Leak Hood Fell Owe": "For he's a jolly good fellow",
                   "Fur Chin Ollie Foil": "Virgin Olive Oil",
                   "Hiawatha dean edge van pyre": "I was a teenage vampire",
                   "Hide Hen Tickled Wins": "Identical Twins",
                   "hint a few width diva umpire": "Interview with a vampire",
                   "Hoe Pin-Up Hits Depot Lease": "Open Up! It's The Police",
                   "Hype People Earth Duh Hey": "Happy Birthday",
                   "Ice Mail Ask Hunk": "I smell a skunk",
                   "Isle Of View": "I love you",
                   "It Chief Heat": "Itchy feet",
                   "Jog Clay Die Scream": "Chocolate Ice Cream",
                   "Kitten Scene Gulf Aisle": "Get in single file",
                   "Know Ozark": "Noah's Ark",
                   "Ladle Rat Rotten Hut": "little Red Riding Hood",
                   "Law Duff There Inks": "Lord of the Rings",
                   "Moe's Art": "Mozart",
                   "My Kojak Sun": "Michael Jackson",
                   "Ooze Kid Sing Sand Tough Claws": "Who's Kissing Santa Claus",
                   "Pea Sank White": "Peace and Quiet",
                   "Pie Rate Softy Care Hip Been": "Pirates of the Carribean",
                   "Pier Steers": "Pierced ears",
                   "Rim Him Birth Owl Limo": "Remember The Alamo",
                   "Sand Tack Laws": "Santa Claus",
                   "Space You'll Limp Picks": "Special Olympics",
                   "Thick awe loved hoot he": "The call of duty",
                   "Thick Hull Foam Heck Sicko": "The Gulf of MeXico",
                   "Up Hair Hush Ooze": "A Pair Of Shoes",
                   "We Shy Worth Hare": "Wish I was there",
                   "Went Hurl Hymn Pick Aims": "Winter Olympic Games",
                   "Wheel Yum Air Ream He": "Will You Marry Me",
                   "Wok Lie Canny Chip Shun": "Walk like an Egyptian",
                   "Yell Hope Hey Jess": "Yellow Pages",
                   "Yore Luke Ink Hood": "You're looking good",
                   "Ape Haul Oath Hurt Dean": "Apollo Thirteen",
                   "Tote Hall Reek Hall": "Total Recall",
                   "Zola Reek Lips": "Solar Eclipse",
                   "My Cull Chore Den": "Michael Jordan",
                   "Sell Your Laugh Hone": "Cellular Phone",
                   "Made Divorce Pea Whiff Ewe": "May The Force Be With You",
                   "Four Ghetto Fur": "Fork It Over",
                   "Eggs Hearse Sized Hay Lee": "Exercise Daily",
                   "Kenya Ear Mean How": "Can You Hear Me Now?",
                   "Doll May Shuns": "Dalmatians",
                   "Lass Twill Ant Taste A Mint": "Last Will And Testament",
                   "Weed Owns Tan Ditch Ants": "We Don't Stand A Chance",
                   "Wreck You Lure Hoard He Calf": "Regular Or Decaf?",
                   "Shook Hurl His Scum": "Sugarless Gum",
                   "Thief Armor Indeed Hell": "The Farmer In The Dell",
                   "Warren Peas": "War And Peace",
                   "Tie Man Dug Hen": "Time And Again",
                   "Freeze Age Ha! Leak Hood Fell Owe": "For He's A Jolly Good Fellow",
                   "Abe Lesson Indy Skies": "A Blessing In Disguise",
                   "Bay Beach Hemp Ooh": "Baby Shampoo",
                   "Appears Neigh Full": "A Pierced Navel",
                   "Come Pew Turf High Russ": "Computer Virus",
                   "Chest Jew Wade Aim In It": "Just You Wait A Minute",
                   "Caress Peak Reamed Hone Huts": "Krispy Kreme Doughnuts",
                   "Yang Keyed Ooh Dealt Andy": "Yankee Doodle Dandy",
                   "Is Bunch Pops Queer Pans": "Sponge Bob Square Pants",
                   "Eyed Rink Gay Tour Eight": "I Drink Gatorade",
                   "Gasp Earthy Fur End Lee Coast": "Casper The Friendly Ghost",
                   "Day Demand War Kink": "Dead Man Walking",
                   "Abe Aura Her She's Chalk Lit": "A Bar Of Hershey's Chocolate",
                   "Heart Official Ant Heller Gents": "Artificial Intelligence",
                   "Soon Knees Hide Hup": "Sunny Side Up",
                   "Muff Heater Gold": "My Feet Are Cold",
                   "Says Amy's Treat": "Sesame Street",
                   "Strain Jazzin' Dean Height": "Strangers In The Night",
                   "Free Quaintly As Quest Shuns": "Frequently Asked Questions",
                   "More Fee Slaw": "Murphy's Law",
                   "These Moe King Hun": "The Smoking Gun",
                   "Hopper Tune Hit Teen Ox": "Opportunity Knocks",
                   "Oz Temp Hours": "Austin Powers",
                   "Swede Hans Hour Poke": "Sweet And Sour Pork",
                   "Huff Oral Heave Glow Fur": "A Four-leaf Clover",
                   "Ran Dumb Max Suck Highness": "Random Acts Of Kindness",
                   "The Odor Rows Of Felt": "Theodore Roosevelt",
                   "Weed Hid Dents Tart Thief Higher": "We Didn't Start The Fire",
                   "En Wipe He Deep Lou": "NYPD Blue",
                   "Lou Quad Hive Cot": "Look What I've Got",
                   "Tooth Her Mack Her Rain Her": "Do The Macarena",
                   "State Who Their Height": "Stay To The Right",
                   "Damp Obey Floor Eater": "Tampa Bay, Florida",
                   "Sit Jerk Lock": "Set Your Clock",
                   "Paw Rolfe Eye Owe Lay Shun": "Parole Violation",
                   "I'm Issues Home Hutch": "I Miss You So Much",
                   "Dawn Dutch Mice Tough": "Don't Touch My Stuff",
                   "High Dance Eek": "Hide And Seek",
                   "Whole Imp Pig Aims": "Olympic Games",
                   "Tray Sure Aisle Hand": "Treasure Island",
                   "Lee On Hard Odie Cap Rio": "Leonardo DiCaprio",
                   "Canoes He Wad Ice He": "Can You See What I See?",
                   "Eighth Reap Ease Hoot": "A Three-Piece Suit",
                   "Mare Itch Prop Owes All": "Marriage Proposal",
                   "These Hound Doff Moo Sick": "The Sound Of Music",
                   "We Knit Train Sip Oars": "When It Rains, It Pours",
                   "Manna Cue Her": "Manicure",
                   "Read Hick Yule Us": "Ridiculous",
                   "Theme Ask Cough Sore Owe": "The Mask Of Zorro",
                   "Gnu Your Cassidy": "New York City",
                   "I'm On Stairs Sink": "Monsters Inc",
                   "Nor Thumb Air Reckon": "North American",
                   "Sadder Dane Height Fee Fur": "Saturday Night Fever",
                   "Haystack Up Hank Aches": "A Stack Of Pancakes",
                   "Peek Nicked Ape Bull": "Picnic Table",
                   "Dozen May Kenny Cents Tomb He": "Doesn't Make Any Sense To Me",
                   "Sioux Punk Rack Hearse": "Soup And Crackers",
                   "Fur Stand Form Host": "First And Foremost",
                   "Wands Up Pawn Eight I'm": "Once Upon A Time",
                   "Sym Bell Has Abe He Sea": "Simple As A-B-C",
                   "Plea Sway Tube Ease Heated": "Please Wait To Be Seated",
                   "Inn Tooth Hen Heir": "Into Thin Air",
                   "Hoop Side Hid Ditto Ken": "Oops I Did It Again",
                   "Mine Ore A Teary Port": "Minority Report",
                   "Rot Into Thick Oar": "Rotten To The Core",
                   "Thesis Sawn Who Tomb He": "This Is All New To Me",
                   "Sea Yule Hater": "See You Later",
                   "Fun Ella Eyes": "Vanilla Ice",
                   "Why Emcee Hay": "Ymca",
                   "Theme Are Ink Ore": "The Marine Corps",
                   "May Cuss Suck Jest Chin": "Make A Suggestion",
                   "Par Keens Pace": "Parking Space",
                   "Rome He Owe Hand Jewelry Yet": "Romeo And Juliet",
                   "Wide Hidden Chews Haze Hoe": "Why Didn't You Say So?",
                   "Hit Stoop Add": "It's Too Bad",
                   "May Churl Eek Bays Paul": "Majore League Baseball",
                   "Sue Purse Eye Smee": "Super Size Me",
                   "Wall Come Island Mash Ooze": "Walk A Mile In My Shoes",
                   "For Dee Hay Towers": "48 Hours",
                   "Hoe Min Proof Mint": "Home Improvement",
                   "Pick Sin Herb Lank Hit": "Pigs In A Blanket",
                   "Hint A Few Width Diva Umpire": "Interview With The Vampire",
                   "Dust Herb Ink Dap Peas": "Disturbing The Peace",
                   "Ace Heck Hunch Ants": "A Second Chance",
                   "Hype Ledger Legions Tooth Affleck": "I Pledge Allegiance To The Flag",
                   "Thief Hearse Late He": "The First Lady",
                   "Reese Urchin Deep Element": "Research And Development",
                   "Say Fit Fray Ray Need Hey": "Save It For A Rainy Day",
                   "Plea Sleeve Amass Itch": "Please Leave A Message",
                   "Aim Adder Rough Open Yen": "A Matter Of Opinion",
                   "Go Form Hints Pending": "Government Spending",
                   "Own Late Aches Aim Men Hit": "Only Takes A Minute",
                   "Were That Sway Ten Cold": "Worth Its Weight In Gold",
                   "Ape He Street He": "A Peace Treaty",
                   "Hit Snotty Fin Clothes": "It's Not Even Close",
                   "Mash Who'll Aces Sun Tide": "My Shoelace Is Untied",
                   "Plea Center Europe As Ward": "Please Enter Your Password",
                   "Fooled Forth Halt": "Food For Thought",
                   "Ace Cam Mar Test": "A Scam Artist",
                   "Sea Can't Higher Dove Fit": "Sick And Tired Of It",
                   "Mass Turk Hard": "MasterCard",
                   "Dock Terse Oar Duhs": "Doctor's Orders",
                   "Oozer Fray Duff Deep Pig Pad Woof": "Who's Afraid Of The Big Bad Wolf?",
                   "Rye Terse Gramp": "Writer's Cramp",
                   "Ace Height Force Oar Rise": "A Sight For Sore Eyes",
                   "Ditch Chews Haze Hum Thin": "Did You Say Something?",
                   "Bed Chirp Autumn Doll Her": "Bet Your Bottom Dollar",
                   "Oar He Oak Hooky": "Oreo Cookie",
                   "Srobe Bury Sink Ream": "Strawberries And Cream",
                   "Dark Turf Rank Inns Tyne": "Dr. Frankenstein",
                   "Dawn Biafra Eight Duff Deed Arc": "Don't Be Afraid Of The Dark",
                   "Sick Steamy Knits": "Sixty Minutes",
                   "Tray Dirge Hose Mar Kit": "Trader Joe's Market",
                   "Lawn Hoarder": "Law & Order",
                   "Lair Fink Gout Lout": "Laughing Out Loud",
                   "Tock Toothy And": "Talk To The Hand",
                   "Aim Hilly Hindu Juan": "A Million To One",
                   "Tack Seed Rye Fur": "Taxi Driver",
                   "Drew Thawed Air": "Truth Or Dare",
                   "Hen Dean Apple Us": "Indianapolis",
                   "Pry Damp Ray Chewed Hiss": "Pride And Prejudice",
                   "Theme Hum He Reed Urns": "The Mummy Returns",
                   "Ands Inure Pans": "Ants In Your Pants",
                   "Dew Wino Hue": "Do I Know You?",
                   "Hive Ale Ding Leash": "I Failed English",
                   "Hell Beau Soft Teat Able": "Elbows Off The Table",
                   "Knee Says Sand Nay Fuse": "Nieces And Nephews",
                   "Pie Rate Softy Car Hip Been": "Pirates Of The Caribbean",
                   "Foyer Inn Form Hay Shun": "For Your Information",
                   "Deep Hatch Hell Oar Rhett": "The Bachelorette",
                   "Raid He Owe Wack Tiff": "Radioactive",
                   "Up Racked Hick Gulch Oak": "A Practical Joke",
                   "I'm Ill Yon Dull Hers": "A Million Dollars",
                   "Pa Pie These Hail Herman": "Popeye The Sailor Man",
                   "Eggs Rave Fish Hun": "X-Ray Vision",
                   "Kay Belt Ella Fission": "Cable Television",
                   "Ladle Rut Writing Good": "Little Red Riding Hood",
                   "Thread Why Tanned Blew": "The Red, White And Blue",
                   "By Chore Dung": "Bite Your Tongue",
                   "Welk Hum Ohm": "Welcome Home",
                   "Canoe Key Pace He Grit": "Can You Keep A Secret?",
                   "Weenie Toot Hawk": "We Need To Talk",
                   "Noggin Hock Ooze Their": "Knock! Knock! Who's There?",
                   "Lore Deaf Immerse He": "Lord Have Mercy",
                   "Lie Berry Off Cone Grass": "Library Of Congress",
                   "Uke Ant An Dell Tat Ruth": "You Can't Handle The Truth",
                   "Ewe Nigh Ted Kink Dumb": "United Kingdom",
                   "High Den Tee Teeth Heft": "Identity Theft",
                   "Sigh Code Ram Aah": "Psycho-Drama",
                   "When Hurt Ache Saw": "Winner Takes All",
                   "Hint Earn Hall Rougher New Sir Face": "Internal Revenue Service",
                   "Wish Hood Oven Own": "We Should Have Known",
                   "Tote Ali Calypso Thee Art": "Total Eclipse Of The Heart",
                   "Mack Her Owe Knee Inch He's": "Macaroni And Cheese",
                   "Bay Beak Hot Bach": "Baby Got Back",
                   "Hug Tomb Eye Ed": "You Go To My Head",
                   "Prey Tee Womb Anne": "Pretty Woman",
                   "Poe Lease Deep Heart Mint": "Police Department",
                   "Howdy Vest Fuzz Juan": "How The West Was Won",
                   "Dawned Ease Mi": "Don't Tease Me",
                   "Pay Perk Lips": "Paper Clips",
                   "Raw Key Row Die Scream": "Rocky Road Ice Cream",
                   "Jewel Us Seize Her": "Julius Ceasar",
                   "Bee Foreign Halved Her": "Before And After",
                   "He-Man Seep Pay Shun": "Emancipation",
                   "Ma Neat Inks Hark": "Man-Eating Shark",
                   "Tin Purse Scent Desk Hound": "Ten Percent Discount",
                   "Too Niece Oprah Know": "Tony Soprano",
                   "Hen Day Anna's Date": "Indiana State",
                   "Height Whole Chews Hoe": "I Told You So",
                   "Fee Henna Walls Moo Sick": "Wienna Waltz Music",
                   "These Ant Are Claws": "The Santa Clause",
                   "Sit Ease Lick Hearse": "City Slickers",
                   "Mike Arson Dish Hop": "My Car's In The Shop",
                   "Grin Etch Fell Itch": "Greenwich Village",
                   "Henna He Bawdy Their": "Anybody There?",
                   "Eye Mull Of Mush Sheen": "I'm A Love Machine",
                   "Use Mel Could": "You Smell Good",
                   "Lew Eve Falcon Duck He": "Louisville, Kentucky",
                   "Ape Hack Awful Eyes": "A Pack Of Lies",
                   "Lawn Gopher Do": "Long Overdue",
                   "Ow Tough Sequins": "Out Of Sequence",
                   "Won Hunt Dread Hollers": "One Hundred Dollars",
                   "Sock Herb Hauls": "Soccer Balls",
                   "Lat Stool Hunch": "Let's Do Lunch",
                   "Eighty Part Mints Tore": "A Department Store",
                   "Eyes Cool Valley Dick Tour He An": "High School Valedictorian",
                   "Lock Sand Bay Gulls": "Lox And Bagels",
                   "Stow Len Key Says": "Stolen Kisses",
                   "Width Ought Eight Rays": "Without A Trace",
                   "Pooh Seek Hats": "Pussycats",
                   "Loaf Verse Try Ankle": "Lover's Triangle",
                   "You Knee Copper Two Needy": "Unique Opportunity",
                   "Rap Hun Sell": "Rapunzel",
                   "Law San Jail Lust Dimes": "Los Angeles Times",
                   "A Taco Think Loans": "Attack Of The Clones",
                   "Than Cue Button Hoe": "Thank You",
                   "Hugh Knigh Teds Dates": "United States",
                   "Hefty Chew Fit Swear Hit": "If The Shoe Fits, Wear It",
                   "Wad Abe Hummer": "What A Bummer!",
                   "Some Hero Limp Hicks": "Summer Olympics",
                   "Noose Raid He Owe": "News Radio",
                   "Hun Fork Kit Table": "Unforgettable",
                   "Eggs Cape For Mal Cat Razz": "Escape From Alcatraz",
                   "Some Ark Amp Ounce Yule Air": "Summer Camp Counselor",
                   "Donut Hoe Pin Beef Fork Wrist Mess": "Do Not Open Before Christmas",
                   "Huh Vanna Cue Bah": "Havana Cuba",
                   "Row Man Call Lease He Hem": "Roman Coliseum",
                   "Why Tell Infants Ale": "White Elephant Sale",
                   "Freez Ham Pulse": "Free Samples",
                   "Arrest Mike Ace": "I Rest My Case",
                   "Thirst Hay Even Ink": "Thursday Evening",
                   "Wad Abe Hunch Off Nuns Hence": "What A Bunch Of Nonsense",
                   "Huh Mere Eye Can Eye Dull": "American Idol",
                   "Abe Hold Faye Sly": "A Bold-Faced Lie",
                   "Aisle Me Chew Have Weigh": "I'll Meet You Halfway",
                   "Tempo Might Hung": "Tip Of My Tongue",
                   "Nod Itch Ants": "Not A Chance",
                   "Knot Joe Geeze": "Nacho Cheese",
                   "Earl Eat Tibet Earl Eat Who Rice": "Early To Bed Early To Rise",
                   "Hoover Aimed Raw Cheer Habit": "Who Framed Roger Rabbit?",
                   "Pub Lick Ewe Till Itty": "Public Utility",
                   "We Shy Worth Hare": "Wish I Were There",
                   "Play Sings Add Dells": "Blazing Saddles",
                   "High Wetness Snooze": "Eyewitness News",
                   "Abe Earth Daze Hoot": "A Birthday Suit",
                   "Hat Ten Shunned Deaf Asset Tis Hoarder": "Attention Deficit Disorder",
                   "Nest Leak Grunge Jabar": "Nestle Crunch Bar",
                   "Toe Tall Gun Few Shun": "Total Confusion",
                   "Up Hound Hug Round Round": "A Pound Of Ground Round",
                   "Oh Firm Hide Head Potty": "Over My Bead Body",
                   "Hoe Moth Herb Rave": "Home Of The Brave",
                   "Eye Mile Tough Guess": "I'm Out Of Gas",
                   "Us Candle Us Of Hair": "A Scandalous Affair",
                   "Sheik Cons Hoop Fur Thistle": "Chicken Soup For The Soul",
                   "Sex Feed Hunter": "Six Feet Under",
                   "Half Freight Tough Deed Arc": "Afraid Of The Dark",
                   "Deer Leap Heel Hovered": "Dearly Beloved",
                   "Shoe Gird Hone Huts": "Sugar Donuts",
                   "Her Wreath Of Rank Lynne": "Aretha Franklin",
                   "Dew Placate Prince": "Duplicate Prints",
                   "Thesis Nope Lace Furl Eighty": "This Is No Place For A Lady",
                   "These Oop Ream Kurt": "The Supreme Court",
                   "Nativity Merry Cans": "Native Americans",
                   "Fatty Cans Itty": "Vatican City",
                   "Ghetto Four Abe Row Can Art": "Get Over A Broken Heart",
                   "Pull Ease Clothes Theodore": "Please Close The Door",
                   "Thug Yet His Burger Dress": "The Ghettysburg Address",
                   "You Rowed His Knee": "Euro Disney",
                   "Spar Cling What Her": "Sparkling Water",
                   "Nose Moe Kings Own": "No-Smoking Zone",
                   "Deal If Are Ants": "Deliverance",
                   "Amos Ooze": "A Masseuse",
                   "Faye Teller Track Shun": "Fatal Attraction",
                   "Hive Cot Chew Hun Term Ice Kin": "I've Got You Under My Skin",
                   "Eye Screams Hand Witch": "Ice Cream Sandwich",
                   "Eight Hoop Hay": "A Toupee",
                   "Barbie Cute Rips": "Barbecued Ribs",
                   "Fur Chins Ray Chords": "Virgin Records",
                   "Date Roy Pea Stuns": "Detroit Pistons",
                   "Lit Skit Tone Width Hit": "Let's Get On With It",
                   "Pull Ease Leaf Mia Lone": "Please Leave Me Alone",
                   "You Says Dye Erected": "Use As Directed",
                   "Weigh Cup Toothy Fax": "Wake Up To The Facts",
                   "Toot Hence Two Ray Lacks": "Too Tense To Relax",
                   "Puns Offs Teal": "Buns Of Steel",
                   "Mare Heed Width Chilled Run": "Married With Children",
                   "Ewe Hardy Juan Form He": "You Are The One For Me",
                   "Barfs Hope": "Bar Of Soap",
                   "Dream Mennen Eight Hub": "Three Men In A Tub",
                   "Aisle Me Jewel Hater": "I'll Meet You Later",
                   "Eyeed Ream Oaf Gene He": "I Dream Of Genie",
                   "Pea Pill Arf Honey": "People Are Funny",
                   "Win Airy Meds Alley": "When Harry Met Sally",
                   "Theme Alt Ease Falk Inn": "The Maltese Falcon",
                   "Nosh Hun Elsie Cure Itty": "National Security",
                   "Icing Adder Hype Itch": "A Sing At A Hight Pitch",
                   "Hawk Hidden Us Hide": "All Kidding Aside",
                   "Ease Iraq Grew Pea": "He's A Rock Groupie",
                   "Damp Oh Rare Each Hob": "Temporary Job",
                   "Tree Chores Hail Fright": "Treat Yourself Right",
                   "Sip Eighty Dude Ha!": "Zip-A-Dee-Doo-Dah",
                   "Ooze Linus Sit Denny Weigh": "Whose Line Is It Anyway?",
                   "Kwan Tan Nemo Bake You Bah": "Guantanamo Bay, Cuba",
                   "Hemp Yule Lance High Wren": "Ambulance Siren",
                   "Loose Ian Desk Eye Width Dime Hands": "Lucy In The Sky With Diamonds",
                   "Rub Herb Hey Beep Huggy Bum Purse": "Rubber Baby Buggy Bumpers",
                   "Juneau Hawaii Filler Bowed Ewe": "You Know How I Feel About You",
                   "Ear Swan Forth Erode": "Here's One For The Road",
                   "Aid Eye Mud Us Sin": "A Dime A Dozen",
                   "Dawn By Chore Fink Earn Ails": "Don't Bite Your Fingernails",
                   "Few Noose Ooze Hee": "If You Knew Susie",
                   "Safe Hemp Try Fat Try On": "Saving Private Ryan",
                   "Use Header Moth Fuel": "You Said A Mouthful",
                   "Weigh Cup Pin Theme Awning": "Wake Up In The Morning",
                   "May Tricks Reel Owe Dead": "Matrix Reloaded",
                   "Han Dover Theme Honey": "Hand Over The Money",
                   "Ape Arrows Uncle As His": "A Pair Of Sunglasses",
                   "Bigger Scant Beach Who Seers": "Beggars Can't Be Choosers",
                   "Hit Sewn Leap Uphill Of": "It's Only Puppy Love",
                   "Fell Edge Eddie Hit": "Village Idiot",
                   "Dutch Egg Cousin Theme Ale": "The Check Is In The Mail",
                   "Dawn Kim Add Kitty Fin": "Don't Get Mad, Get Even",
                   "Ale Of Huff Air": "A Love Affair",
                   "Sense Cyst Acres": "Census Takers",
                   "Wok Aim Aisle Enema Chews": "Walk A Mile In My Shoes",
                   "Tree Twit Tea Elsie": "Treat With TLC",
                   "Thick Hearse Soft Eve Umpire": "The Curse Of The Vampire",
                   "Pair Neck Ed Late He's": "Barenaked Ladies",
                   "Late Ease Ohm Churn Hal": "Ladies' Home Journal",
                   "Hemp Heath Reap Layer": "MP3 Player",
                   "Dye Lem Form Herder": "Dial M For Murder",
                   "Aid Us Tier Owed": "A Dusty Road",
                   "Dare Saw Weight Such Ants": "There's Always A Chance",
                   "Cain Eye Bayou Ade Rink": "Can I Buy You A Drink?",
                   "Ray Duh Softy Law Stark": "Raiders Of The Lost Ark",
                   "Weed Dupe Hay Percolating": "We Do Paper Collating",
                   "Sigh Cope Ab Bull": "Psychobabble",
                   "Leaf Meal Own": "Leave Me Alone",
                   "Hoe Shin Pray": "Ocean Spray",
                   "Eggs Marx Despot": "X Marks The Spot",
                   "Dock Terse Ooze": "Dr. Seuss",
                   "These Hoop Reams": "The Supremes",
                   "Policed Hymm Delights": "Please Dim The Lights",
                   "Lore Ants Offer Abe Year": "Lawrence Of Arabia",
                   "Hit Says Mall Whirled": "It's A Small World",
                   "Backed Ooze Queer Won": "Back To Square One",
                   "Key Tan Leap Hold": "Kate And Leopold",
                   "Thin Hey Muff Thick Aim": "The Name Of The Game",
                   "Eyes Tink": "I Stink",
                   "Bra Mutter": "Barometer",
                   "Arrow Man Tick Calm Eddy": "A Romantic Comedy",
                   "Fizzy Gal Eggs Ham": "Physical Exam",
                   "Haul Soft Monty Zoo Ma": "Halls Of Montezuma",
                   "Lie Sin Sand Dedges Tray Shun": "License And Registration",
                   "Owed Tube Ill Leech Hoe": "Ode To Billie Joe",
                   "Shake Key Low Kneel": "Shaquille O'Neal",
                   "Weaken Worker Hound Debt": "We Can Work Around It",
                   "Weed Mile Hips": "Read My Lips",
                   "Sit Chores Height Sigh": "Set Your Sights High",
                   "Neigh Verse Sane Heifer": "Never Say Never",
                   "Ice Senate Dew Ewe": "I Sent It To You",
                   "Gray Can Hear": "Greg Kinnear",
                   "Around Dove Apple Laws": "A Round Of Applause",
                   "Elects Hand Earthly Crate": "Alexander The Great",
                   "Huff Fence If Owl": "Offensive Foul",
                   "Marry Addle Ladle Am": "Mary Had A Little Lamb",
                   "Where Tally Hank Of Hick": "Weird Al Yankovic",
                   "Thief Hearse Touch An You Weary": "The First Of January",
                   "Mull Teen Ash Annul Fours": "Multi-National Force",
                   "Juneau Mine Umber": "Do You Know My Number?",
                   "Duke Hum Mere Off Hen": "Do You Come Here Often?",
                   "Thirst Aim Awning": "Thursday Morning",
                   "Theif Hill Art Dell Fee Us Tory": "The Philadelphia Story",
                   "Sent Drill Hum Eric Aah!": "Central America",
                   "Pa's Dram Ease Hand Witch": "Pastrami Sandwich",
                   "My Ham Mead Hole Fins": "Miami Dolphins",
                   "Heap Itched Ape Err Fig Came": "He Pitched A Perfect Game",
                   "Egg Aim Much Egg Curse": "A Game Of Checkers",
                   "Canned Ache My High Saw Few": "Can't Take My Eyes Off You",
                   "Paper Own Heap Heats Aah": "Pepperoni Pizza",
                   "Sink Owed Deem Eye Owe": "Cinco De Mayo",
                   "Tube Row Tacked Ant Surf": "To Protect And Serve",
                   "Us It Ease Liquor": "A City Slicker",
                   "Sigh Ted Fork Un Tempt": "Cited For Contempt",
                   "Peep Elm Hag Oz Scene": "People Magazine",
                   "Lay Bird Hey We Kin": "Labor Day Weekend",
                   "High Wheel Hall Weighs Loaf View": "I Will Always Love You",
                   "Eye Nay Firm Ache Mist Aches": "I Never Make Mistakes",
                   "Awe Haze Could Furl Half": "Always Good For A Laugh",
                   "Hit Sub Pow Dime": "It's About Time",
                   "Key Pits Imp Pills Too Pet": "Keep It Simple Stupid",
                   "Poe Tate Terse Hal Ad": "Potato Salad",
                   "Up Row Fashion Hulls Beaker": "A Professional Speaker",
                   "Toe Gap Hearty": "Toga Party",
                   "Shack Cough Alt Raids": "Jack Of All Trades",
                   "Nope Odd Den Hose Force Your": "Nobody Knows For Sure",
                   "Knee Go She Ate": "Negotiate",
                   "New Disc Hollow Knee": "Nudist Colony",
                   "Row Linen Thumb Honey": "Rolling In The Money",
                   "Tour Tea Etch Hips": "Tortilla Chips",
                   "Witch Weighed Hid Ego": "Which Way Did He Go?",
                   "These Hounds Offs High Lens": "The Sounds Of Silence",
                   "Paws Iffy Go Shin": "Pacific Ocean",
                   "Lawn Done Breach": "London Bridge",
                   "High Weight Who Evan": "Highway To Heaven",
                   "Dawned Rink Hand Arrive": "Don't Drink And Drive",
                   "Dub Hell Chap Ore Dee": "Double Jeopardy",
                   "High Moan Leak Hidden": "I'm Only Kidding",
                   "Lay Surge Urge Hurry": "Laser Surgery",
                   "Yore Luke Ink Hood": "You're Looking Good",
                   "Tot Calm": "Dot Com",
                   "Sew Fiat Tune Yawn": "Soviet Union",
                   "Pain Sills Harp Inner": "Pencil Sharpener",
                   "Lee Gal Heap Lawned": "Legally Blonde",
                   "Go Tan Hatch Heck": "Coat And Hat Check",
                   "Chore Chuff Teach Uncle": "George Of The Jungle",
                   "Was Estrange Lank Wedge": "What A Strange Language",
                   "Stay Tough Arc Handsaw": "State Of Arkansas",
                   "Place Day Shun": "Playstation",
                   "Owe Shins Heel Heaven": "Ocean's Eleven",
                   "Lee Sack Who'd Row": "Lisa Kudrow",
                   "Hiss Statue Gnaw King": "Is That You Knocking?",
                   "Faze Them Hues Sick": "Face The Music",
                   "Deed At Chew Off Lip Buddy": "The Statue Of Liberty",
                   "Noose Eel Hand": "New Zealand",
                   "Reap Lace Mints": "Replacements",
                   "Thud Era Belt Ooze": "The Terrible Twos",
                   "Well Yum Shay Kiss Beer": "William Shakespeare",
                   "Tack Spayer": "Taxpayer",
                   "Hole Kitten Cup Poodle": "Whole Kit And Caboodle",
                   "Fur Scum Fur Surfed": "First Come First Served",
                   "Cur Nells Hand Errs": "Colonel Sanders",
                   "Haste Huff Danny Mull": "A Stuffed Animal",
                   "Intern Ash Shun El Tree Tea": "International Treaty",
                   "Mill Can Goo Keys": "Milk And Cookies",
                   "Peek Czar Hinder Ten Mint": "Pixar Entertainment",
                   "Sill Fester Ant We Tee": "Slyvester And Tweety",
                   "Tie Dull Waif": "Tidal Wave",
                   "Utah Kin Tomb He": "You Talkin' To Me?",
                   "Stay Cake Lame": "Stake A Claim",
                   "Pardon Her Sink Rhyme": "Partners In Crime",
                   "Law Sand Jealous Lay Curse": "Los Angeles Lakers",
                   "Hap Rent Dis": "Apprentice",
                   "Dave Inch Cheek Owed": "Da Vinci Code",
                   "Bah Kin These Addle Ache Ken": "Back In The Saddle Again",
                   "Awl Took Hath Earn How": "All Together Now",
                   "Dutch Mean Them Awning": "Touch Me In The Morning",
                   "Hiney Duck Holes How Ware": "I Need A Cold Shower",
                   "Laws Din Trance Lay Shun": "Lost In Translation",
                   "Nossed Ring Sat Hatched": "No Strings Attached",
                   "Sent Tom Hanukah": "Santa Monica",
                   "Ton Love Love": "Tunnel Of Love",
                   "Chew Ear Thin Ooze": "Did You Hear The News?",
                   "Hook Hut Ditch Ease": "Who Cut The Cheese?",
                   "Annie Turn Awful Lame": "An Eternal Flame",
                   "Since Henna Tea Ojai Owe": "Cincinnati, Ohio",
                   "Mike Lion Tis Inner Scent": "My Client Is Innocent",
                   "Hoe Met Quit Heel Hone": "Home Equity Loan",
                   "Egg Hood Sore Solve Eye Burr": "A Good Souce Of Fiber",
                   "Thick Hard Enough Heed Hen": "The Garden Of Eden",
                   "Wheel Yun Air Ream He": "Will You Marry Me?",
                   "Way Tan Seattle Tude": "Wait-And-See Attitude",
                   "Teller Aber How Did": "Tell Her About It",
                   "Peas Dash He Own Huts": "Pistachio Nuts",
                   "May Cane Aim Foyers Elf": "Make A Name For Yourself",
                   "Grey Niche Car Net He Quit": "Greenwich, Connecticut",
                   "Chain Jeff Pays": "Change Of Pace",
                   "Has Is Tent Men Itcher": "Assistant Manager",
                   "Tubby Horn Hot Tubby": "To Be Or Not To Be",
                   "Shy Niece Sheik Anne's Hal Ad": "Chinese Chicken Salad",
                   "Out Ache Arrow View": "I'll Take Care Of You",
                   "Mean Are Sin Hue Chain": "Me Tarzan, You Jane",
                   "Lace Her Ice Serge Hurry": "Laser Eye Surgery",
                   "Tonier Wards Air Him On Knee": "Tony Awards Ceremony",
                   "Hay Says Anne Dates": "Aces And Eights",
                   "Few Own Lean Hue": "If You Only Knew",
                   "Beak Hall Size Heads Hoe": "Because I Said So",
                   "These Hound Dan Thief Ewe Re": "The Sound And The Fury",
                   "Up Arrow Tin Issues": "A Pair Of Tennis Shoes",
                   "Seethe Rues Rink Crap": "See-Through Shrink Wrap",
                   "Nome Ore Mist Earn Ice Sky": "No More Mister Nice Guy",
                   "Just Us Wheel Yam Wren Quest": "Justice William Rehnquist",
                   "Glassy Fir Dad Fur Ties Mint": "Classified Advertisement",
                   "Empty Fees Speech Ows": "MTV's Beach House",
                   "Kenya Sheik Djibouti": "Can You Shake Your Booty?",
                   "Want Herb Raw": "Wonderbra",
                   "These Cool Awe Frock": "The School Of Rock",
                   "Sew Pop Hurrahs Tar": "Soap Opera Star",
                   "Lie Finch Urine Spa Less He": "Life Insurance Policy",
                   "Goal Damp Error Shoot": "Golden Parachute",
                   "Aim Hunk Hear Inch": "A Monkey Wrench",
                   "Ditch Atoll Cam Hurrah": "Digital Camera",
                   "Kitten Hurl East Heart": "Get An Early Start",
                   "Thief Height Glub": "The Fight Club",
                   "Ache Hunt Trim Aisle": "A Country Mile",
                   "He Stir Paw Raid": "Easter Parade",
                   "Thaw My Teed Holler": "The Almighty Dollar",
                   "Hike Ann Tell Pit": "I Can't Help It",
                   "Keel Her Beast Ink": "Killer Bee Sting",
                   "Fee Knicks Harry's Owner": "Phoenix, Arizona",
                   "Ace Lip Puff That Hung": "A Slip Of The Tongue",
                   "Tooth Hum Sup": "Two Thumbs Up",
                   "Wide Hunch Uke Hall": "Why Don't You Call?",
                   "Seize Hearse Sail Ed": "Ceasar Salad",
                   "Deed Roy Die Guess": "Detroit Tigers",
                   "He Legs Shunned Hey": "Election Day",
                   "Vine Ding Knee Moe": "Finding Nemo",
                   "Soup Herman": "Superman",
                   "Poise Gout Sofa Merry Car": "Boy Scouts Of America",
                   "My Crows Off Tex Sell": "Microsoft Excel",
                   "Lettuce Spray": "Let Us Pray",
                   "Upper Fig Twirled": "A Perfect World",
                   "Hits Tan Treason": "It Stands To Reason",
                   "Gulls Gouts Sofa Mare Eek Her": "Girl Scout Of America",
                   "Berth Daze Hoot": "Birthday Suit",
                   "Sham Paint Host": "Champagne Toast",
                   "Up He Such Ease": "A Piece Of Cheese",
                   "Swede Boat Eight Dope Eye": "Sweet Potato Pie",
                   "Paper Fum Ooh Fee": "Pay-Per-View Movie",
                   "Lee Hone Art Goudh Dove Inch He": "Leonardo Da Vinci",
                   "Hen Deep Hen Danced Hay": "Independence Day",
                   "Disguise They'll Him It": "The Sky's The Limit",
                   "Hum Era Gun Egg Suppress": "American Express",
                   "Mirror Called Rug": "Miracle Drug",
                   "Spike Ids": "Spy Kids",
                   "We Loaf Ore Chin": "Wheel Of Fortune",
                   "Oz Tin Tech Sass": "Austin, Texas",
                   "May Kick Wick": "Make It Quick",
                   "Fair Wren Night": "Fahrenheit",
                   "My Ham Eve Ice": "Miami Vice",
                   "Haul Weigh Sewn Mimi Hind": "Always On My Mind",
                   "Drum Attic Lime Acts": "Dramatic Climax",
                   "Comet He Affair Hearse": "Comedy Of Errors",
                   "Ray Sink Air Reese Owner": "Raising Arizona",
                   "Led Skit Auto Fear": "Let's Get Out Of Here",
                   "Weep Hay Holes Ale": "We Pay Wholesale",
                   "Pay Per Row Says": "Paper Roses",
                   "High Seed Head Pee Pull": "I See Dead People",
                   "Deed Hay Off Tour Tomb Arrow": "Fur Chin Ollie Foil",
                   "Varoom Deep Belt Holes": "For Whom The Bell Tolls",
                   "Pop Hair Yahtzee": "Paparazzi",
                   "Loss Vague Ask Hussy Know": "Las Vegas Casino",
                   "Nuke Id Sun Deep Lock": "New Kids On The Block",
                   "Chest Beat Wean Husk Hurls": "Just Between Us Girls",
                   "You Knee Verse Sails Duty Owes": "Universal Studios",
                   "Lose He An Up Her Chess": "Louisiana Purchase",
                   "Lee Tell Louse Honda Prayer He": "Little House On The Prairie",
                   "Match Hick Kate Paul": "Magic 8-ball",
                   "Skoal Elastic Hap Tee Tude Taste": "Scholastic Aptitude Test",
                   "Yule Lees Mime Hind": "You'll Ease My Mind",
                   "Pole Eddy Clicker Wrecked": "Politically Correct",
                   "Hello Win Dressed Morgue Itch": "A Low-Interest Mortgage",
                   "Pitchers Heat Bell Town": "Put Your Seat Belt On",
                   "Hun Door Hen Easer Come Stan Says": "Under Any Circumstances",
                   "Haft Ermine Dun Height": "After Midnight",
                   "Gay Gummy Width Ace Boon": "Gag Me With A Spoon",
                   "Dawned Hey Guinea Chants His": "Don't Take Any Chances",
                   "Eyed Rye Fan Issue Fee": "I Drive An SUV",
                   "Age Us Dissolved Deep Ease": "A Justice Of The Peace",
                   "Force Ease Hun Sew Tell": "Four Seasons Hotel",
                   "Iran Alt Aweigh Ohm": "I Ran All The Way Home",
                   "Wrist Hush Herd": "Rest Assured",
                   "Police Collar Dock Tour": "Please Call A Doctor",
                   "Sin A Men Sure Grr!": "Cinnamon Sugar",
                   "Cuff Hearse Dory": "Cover Story",
                   "Chew Lie Thief Oath": "July The Forth",
                   "Chain Solve Fad Dress": "Change Of Address",
                   "Ball Stunk Lamp Shouter": "Boston Clam Chowder",
                   "Bloop Lades Pay Shell": "Blue Plate Special",
                   "Baby Beef Ace": "Baby Face",
                   "Bah Fee Theif Amp Hires Layer": "Buffy The Vampire Slayer",
                   "Ache Hatter Mia Words": "Academy Awards",
                   "Share Ilk Row": "Sheryl Crow",
                   "Mile Hip Czars Healed": "My Lips Are Sealed",
                   "Yule Bizarre He": "You'll Be Sorry",
                   "Scene Curse Whim": "Sink Or Swim",
                   "Knee Gull Odie Yon": "Nickelodeon",
                   "Eight Addled Ale": "A Tattle Tale",
                   "Essay Madder Rough Act": "As A Matter Of Fact",
                   "See Chores Elf": "Seat Yourself",
                   "Pooh Purse Coo Purr": "Pooper Scooper",
                   "Loaf Hem Anne Leaf Hem": "Love 'Em And Leave 'Em",
                   "Sheik Hog Hope Airs": "Chicago Bears",
                   "Reef Hing Off Dean Herds": "Half Reed Hummed He Canary",
                   "Ewe Hardy We Gus Slink": "You Are The Weakest Link",
                   "Dawn Beak Rule": "Don't Be Cruel",
                   "Wad Ape Hair": "What A Pair",
                   "Portal Ann Dory Gun": "Portland, Oregon",
                   "Miss Turn High Sky": "Mister Nice Guy",
                   "May King Gout": "Making Out",
                   "Twin Tea Juan Dan Dover": "Twenty-One And Over",
                   "These Eye Lents Softy Lamps": "The Silence Of The Lambs",
                   "May Kind Thief Id He Owe": "Making The Video",
                   "Oak Abe Abe": "Okay",
                   "Able Ink Gun": "Abe Lincoln",
                   "Dawn Ways Might I'm": "Don't Waste My Time",
                   "Abe Ax Heat Rye Fur": "A Back Seat Driver",
                   "Awe Mile Of": "All My Love",
                   "Agree Seize Boon": "A Greasy Spoon",
                   "Check Cove Fault Raids": "Jack Of All Trades",
                   "Hive Cot Yearn Umber": "I've Got Your Number",
                   "Owl Yukon Heat Buff Hay": "All You Can Eat Buffet",
                   "These Tars Angle Ban Her": "The Star Spangled Banner",
                   "Par Dummy": "Pardon Me",
                   "Dew June Hoe Mine Aim": "Do You Know My Name?",
                   "Dew Ache Who Gulls Urge": "Do A Google Search",
                   "Dawn Peek Yearn Hose": "Don't Pick Your Nose",
                   "Bun Crock Moo Sick": "Punk Rock Music",
                   "Ache Wrist Much Air Hull": "A Christmas Carol",
                   "Ache Hand Helen Dee Win": "A Candle In The Wind"}

        randomPrompt = random.choice(list(prompts))
        randomPromptAnswer = prompts[randomPrompt]
        await ctx.send(randomPrompt.title())
        await ctx.send(f"answer: ||{randomPromptAnswer}||")


def setup(bot):
    bot.add_cog(RandomCommands(bot))
